(() => {
const P = window.DELTA_PROPERTIES || [];
const money = n => n >= 10000000 ? "₹" + (n/10000000).toFixed(2).replace(/\.00$/,"") + " Cr" : n >= 100000 ? "₹" + (n/100000).toFixed(2).replace(/\.00$/,"") + " L" : "₹" + n.toLocaleString("en-IN");
const card = p => `<article class="property-card"><a href="realty-property.html?id=${encodeURIComponent(p.id)}" class="photo"><img src="${p.image}" alt="${p.title}"><span class="tag">${p.tag||"Property"}</span>${p.verified?'<span class="verified"><i class="fa-solid fa-circle-check"></i> Verified</span>':""}</a><div class="pc-body"><div class="price">${money(p.price)} ${p.mode==="rent"?'<small>/ month</small>':""}</div><h3><a href="realty-property.html?id=${encodeURIComponent(p.id)}">${p.title}</a></h3><p class="location"><i class="fa-solid fa-location-dot"></i> ${p.locality}, ${p.city}</p><div class="facts">${p.beds?`<span><b>${p.beds}</b> BHK</span>`:""}<span><b>${p.area.toLocaleString("en-IN")}</b> sq.ft.</span><span>${p.type}</span></div></div></article>`;
function queryObj(){return new URLSearchParams(location.search)}
function renderFeatured(){const el=document.getElementById("featuredGrid"); if(el) el.innerHTML=P.slice(0,4).map(card).join("")}
function renderListings(){const grid=document.getElementById("listingGrid"); if(!grid)return; const q=queryObj(); let mode=q.get("mode")||"", type=q.get("type")||"", search="", beds="", budget=""; const fs=document.getElementById("fSearch"), fm=document.getElementById("fMode"), ft=document.getElementById("fType"), fb=document.getElementById("fBeds"), fbud=document.getElementById("fBudget"); if(fm)fm.value=mode; if(ft && type){const match=[...ft.options].find(o=>o.value.toLowerCase()===type.toLowerCase()); if(match)ft.value=match.value}
const draw=()=>{search=fs.value.toLowerCase();mode=fm.value;type=ft.value;beds=fb.value;budget=fbud.value;let arr=P.filter(p=>(!mode||p.mode===mode)&&(!type||p.type.toLowerCase()===type.toLowerCase())&&(!search||`${p.city} ${p.locality} ${p.title}`.toLowerCase().includes(search))&&(!beds||p.beds>=Number(beds))&&(!budget||(()=>{const [a,b]=budget.split("-").map(Number);return p.price>=a&&p.price<=b})())); grid.innerHTML=arr.length?arr.map(card).join(""):`<div class="empty"><i class="fa-regular fa-face-frown"></i><h2>No matching properties yet</h2><p>Try changing your filters or <a href="realty-post.html">list a property</a>.</p></div>`; const c=document.getElementById("resultCount");if(c)c.textContent=`${arr.length} properties found`; const t=document.getElementById("listingTitle");if(t)t.textContent=mode==="rent"?"Properties for Rent":type?`${type} Properties`:"Properties`;};
[fs,fm,ft,fb,fbud].forEach(x=>x&&x.addEventListener("input",draw));document.getElementById("reset")?.addEventListener("click",()=>{fs.value=fm.value=ft.value=fb.value=fbud.value="";draw()});draw()}
function renderProperty(){const el=document.getElementById("property");if(!el)return;const id=queryObj().get("id"),p=P.find(x=>x.id===id)||P[0];if(!p){el.innerHTML="<div class='empty'><h2>Property not found</h2></div>";return}document.title=`${p.title} | Delta Realty`;el.innerHTML=`<div class="detail-grid"><div><img class="detail-image" src="${p.image}" alt="${p.title}"><div class="detail-badges">${p.verified?'<span class="verified large"><i class="fa-solid fa-circle-check"></i> Delta Verified</span>':""}<span class="tag">${p.tag||"Property"}</span></div></div><div class="detail-copy"><span class="eyebrow">${p.mode==="rent"?"FOR RENT":"FOR SALE"} • ${p.type}</span><h1>${p.title}</h1><p class="location"><i class="fa-solid fa-location-dot"></i> ${p.locality}, ${p.city}</p><div class="detail-price">${money(p.price)} ${p.mode==="rent"?"<small>/ month</small>":""}</div><div class="facts big">${p.beds?`<span><b>${p.beds}</b> BHK</span>`:""}<span><b>${p.baths}</b> Baths</span><span><b>${p.area.toLocaleString("en-IN")}</b> sq.ft.</span></div><p>${p.description}</p><div class="detail-actions"><a class="primary" href="https://wa.me/?text=${encodeURIComponent("I am interested in "+p.title+" on Delta Realty.")}" target="_blank"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a><button class="outline" onclick="alert('Lead captured in this demo. Production version will send it to the Delta admin dashboard.')">Request Site Visit</button></div></div></div>`}
function setupHome(){document.getElementById("homeSearch")?.addEventListener("submit",e=>{e.preventDefault();const q=new URLSearchParams();const loc=document.getElementById("qLocation").value,type=document.getElementById("qType").value,b=document.getElementById("qBudget").value;const mode=document.querySelector(".tab.active")?.dataset.mode||"buy";if(loc)q.set("q",loc);if(type)q.set("type",type);if(b)q.set("budget",b);if(mode)q.set("mode",mode);location.href="realty-listings.html?"+q.toString()});document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active")}));document.querySelectorAll(".quick button").forEach(b=>b.addEventListener("click",()=>{document.getElementById("qLocation").value=b.dataset.city}));}
function setupForm(){const f=document.getElementById("propertyForm");if(!f)return;f.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));const saved=JSON.parse(localStorage.getItem("deltaPropertyDrafts")||"[]");saved.push({...d,id:"local-"+Date.now(),createdAt:new Date().toISOString()});localStorage.setItem("deltaPropertyDrafts",JSON.stringify(saved));document.getElementById("formMsg").textContent="Property saved as a draft for review. Connect Supabase/backend before accepting real customer submissions.";f.reset()})}
document.getElementById("year")&&(document.getElementById("year").textContent=new Date().getFullYear());renderFeatured();renderListings();renderProperty();setupHome();setupForm();
})();